### ISSUE TITLE
No timestamp when using docker-compose

### ISSUE THREAD

**Issue by cookandy** [digital-wonderland/docker-logstash-forwarder#22]
Hi,

Thanks again for the great project.  I am running into an issue when starting this image via docker-compose.  To give you some background, when I start the container manually, via the following command, it works.  

```
docker run -it --rm -v /var/lib/docker:/var/lib/docker -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/share/logstash-forwarder:/mnt/logstash-forwarder -e LOGSTASH_HOST=logstash.service.consul:5043 -e SERVICE_NAME=logstash-forwarder logstash-forwarder
```

When I start the container this way, the log gets created and sent to logstash as expected.  I am able to configure an index pattern (based on either `@timestamp` or `time` field names) as I would expect.  

However, if I start this image via docker-compose using the following config, it doesn't seem to work.

```
logstash-forwarder:
  image: logstash-forwarder:latest
  volumes:
    - /var/lib/docker:/var/lib/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/share/logstash-forwarder:/mnt/logstash-forwarder
  environment:
    LOGSTASH_HOST:          "logstash.service.consul:5043"
    SERVICE_NAME:            "logstash-forwarder"
  restart: always
```

When I start the container this way, the log is sent to logstash correctly, but there are no timestamps in it.  That is, within Kibana I can see the logstash-* log, however, there is no way to configure an index based on time (as the `@timestamp` and `time` field names don't exist).  

Do you have any ideas why this is happening?  I'm not sure if it's a limitation with docker-compose, or something else.

Thanks!

**Comment by digital-wonderland** [comment]
To be honest I'm a bit baffled how this could happen since _docker-logstash-forwarder_ merely generates a _logstash-forwarder_ config and restarts an instance of it whenever that config changes - as in the whole log forwarding is done by _logstash-forwarder_. How this could be influenced by using _docker-compose_ I have no idea. Last but not least the timestamp must be in there since you said you have those day based logstash indices within Elasticsearch.

Can you please provide a minimal docker-compose config with the full ELK stack & some example container which allows to reproduce this issue?

**Comment by cookandy** [comment]
Hello,

I am also confused how docker-compose would affect this. I am using this project as my base for my ELK stack:

https://github.com/deviantony/docker-elk

I'm pretty much using the project as-is, out of the box - with the exception of the certificate.  I've generated a self-signed cert and changed the port from `5000` to `5043`.

Here is a copy of my docker-compose for the ELK stack:

```yaml
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5043:5043"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
``` 

Within the `logstash/config` folder, I've got my certs and my logstash.conf:

```
input {
  lumberjack {
    codec => "json"
    # The port to listen on
    port => 5043
    # The paths to your ssl cert and key
    ssl_certificate => "/etc/logstash/conf.d/logstash-forwarder.crt"
    ssl_key => "/etc/logstash/conf.d/logstash-forwarder.key"
  }
}

filter {
  if [log] =~ "Consul returned no data" {
    drop { }
  }
}

## Add your filters here

output {
        elasticsearch {
		hosts => "elasticsearch:9200"
        }
}
```

I am using OS X and am using docker-machine.  I have tried to run the ELK stack on the same machine as the logstash-forwarder, and on different machines... it makes no difference.  For the sake of this example, I will be launching the ELK stack on one docker-machine (**192.168.99.100**) and the logstash-forwarder on another docker-machine (**192.168.99.101**)

Once the ELK stack is up and running, I can verify that there are no logstash logs by looking at Kibana

![](https://dl.dropboxusercontent.com/u/64324/github/1.png)

If I start the container with with the following `docker run` command, it works fine.

```
docker run -it --rm -v /var/lib/docker:/var/lib/docker:ro -v /var/run/docker.sock:/var/run/docker.sock -v /Users/andy/Desktop/docker-elk/logstash-forwarder:/mnt/logstash-forwarder -e LOGSTASH_HOST=192.168.99.100:5043 -e SERVICE_NAME=logstash-forwarder logstash-forwarder
```

I can see from the docker logs that it sent events to the server:

```
2015/11/16 15:35:12.956706 Setting trusted CA from file: /mnt/logstash-forwarder/logstash-forwarder.crt
2015/11/16 15:35:12.958899 Connecting to [192.168.99.100]:5043 (192.168.99.100) 
2015/11/16 15:35:13.176558 Connected to 192.168.99.100
2015/11/16 15:35:18.775672 Registrar: processing 49 events
```

And when I go into Kibana, I can see that the logs have been generated, and contain timestamps:

![](https://dl.dropboxusercontent.com/u/64324/github/2.png)

All good so far....

However, when I start the container using my docker-compose file, it doesn't work.  Here's my config (I've tried with and without the privileged mode):

```yaml
logstash-forwarder:
  privileged: true
  image: logstash-forwarder:latest
  volumes:
    - /var/lib/docker:/var/lib/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - /Users/andy/Desktop/docker-elk/logstash-forwarder:/mnt/logstash-forwarder
  environment:
    LOGSTASH_HOST:          "192.168.99.100:5043"
    SERVICE_NAME:            "logstash-forwarder"
  restart: always
```

When the container starts, I can see it send the events to the server as I would expect:

```
logstash-forwarder_1 | 2015/11/16 15:37:40.516077 Setting trusted CA from file: /mnt/logstash-forwarder/logstash-forwarder.crt
logstash-forwarder_1 | 2015/11/16 15:37:40.517623 Connecting to [192.168.99.100]:5043 (192.168.99.100) 
logstash-forwarder_1 | 2015/11/16 15:37:40.706688 Connected to 192.168.99.100
logstash-forwarder_1 | 2015/11/16 15:37:46.222627 Registrar: processing 55 events
```

And when I go look at Kibana, I can see that the logstash server has been picked up by the server (because I have the ability to create the index). However, if I look at the dropdown, there are no timestamp fields

![](https://dl.dropboxusercontent.com/u/64324/github/3.png)

Does this help?  Let me know if you need any more information.  Thanks!
